config/routes.rb
Rails.application.routes.draw do
  devise_for :people, controllers: { sessions: 'devise/sessions' },
                      skip: [:registrations]
  devise_for :clients, skip: :sessions,
                       controllers: { registrations: 'client/registrations' }

  resources 'contacts', only: [:new, :create]
  root 'home#index'

  namespace :backend do
    root 'news#index'

    resources :products
    devise_for :people, :manager, :receptionists, :lifeguards, :trainers,
               skip: :sessions,
               controllers: { registrations: 'backend/registrations' }

    resources :entry_types do
      resources :bought_details, except: [:show, :edit, :update]
      collection do
        get 'bought_list', to: 'entry_types#show'
        get 'search'
      end
    end
    get 'trainers', to: 'people#trainers'

    resources :activities_people, except: [:show, :new, :edit]
    resources :news do
      member do
        post 'like'
      end
      resources :comments, only: [:create, :edit, :update, :destroy]
    end
    resources :work_schedules do
      collection do
        get 'search'
      end
    end
    resources :activities, except: [:show] do
      collection do
        get 'search'
        get 'pool_zone'
        get 'requests'
      end
      member do
        get 'sign_up'
        get 'preview'
        post 'activate'
        post 'deactivate'
      end
    end

    resources :vacations, only: [] do
      collection do
        get 'requests'
        get 'search'
      end
      member do
        post 'accept'
      end
    end

    resources :manage_trainings, only: [:index, :new, :create]
    # Manage vacations
    resources :manage_vacations, only: :index
    resources :individual_trainings, only: [:index, :update, :show, :edit, :search, :destroy] do
      collection do
        get 'search'
      end
    end
    resources :training_costs, except: [:show]
    resources :people, except: [:new, :create] do
      collection do
        get 'search'
      end

      member do
        delete 'remove_photo'
        get 'bought_history'

        resources :individual_trainings, only: [:update, :choose_trainer] do
          collection do
            get 'choose_trainer'
            get 'show', as: 'show'
            get 'show_details'
          end
        end

        resources :trainers, only: [] do
          resources :individual_trainings, param: :ind_training_id
        end
        resources :work_schedules, as: 'manage_schedule' do
          collection do
            get 'new', as: 'new'
            get 'my_schedule', to: 'work_schedules#show', as: 'my'
          end
        end
        resources :vacations, param: :vacation_id, except: [:show]
      end
    end
    resources :statistics, only: [:index]
    # /das/dsa/users?kind=client|manager|
    [:managers, :clients, :receptionists, :lifeguards].each do |type|
      get type, to: 'people#' + type.to_s
    end
  end
end

app/views/shared/_a_searchbar.html.slim
= form_tag search_backend_activities_path, method: :get do
  .input-field.col-md-6
    .input-group-btn
      i.material-icons.prefix type="submit" search
      label for="icon_prefix" Szukaj
      = text_field_tag :query, params[:query], class: "search-query", input_html: {id: 'icon_prefix'}
  .searchbar-fix.col-md-3
    = submit_tag 'Szukaj', class: 'btn btn-primary'

app/views/shared/_back.html.slim
= link_to :back do
  .btn.btn-primary.waves-effect.waves-light
    i.fa.fa-chevron-left
    |  Wróć

app/views/shared/_errors.html.slim
.panel.panel-danger.copyright-wrap#copyright-wrap
  .panel-heading
    | Wystąpiły błędy proszę poprawić:
    button.close data-dismiss="alert" data-target="#copyright-wrap" type="button"
      span aria-hidden="true" ×
      span.sr-only Close
  .panel-body
    ul
      - object.errors.full_messages.each do |msg|
        li= msg

app/views/shared/_et_searchbar.html.slim
/Entry Type searchbar
= form_tag search_backend_entry_types_path, method: :get do
  .input-field.col-md-6
    .input-group-btn
      i.material-icons.prefix type="submit" search
      label for="icon_prefix" Szukaj
      = text_field_tag :query, params[:query], class: "search-query", input_html: {id: 'icon_prefix'}
  .searchbar-fix
    = submit_tag 'Szukaj', class: 'btn btn-primary'

app/views/shared/_it_searchbar.html.slim
= form_tag search_backend_individual_trainings_path, method: :get do
  .input-field.col-md-6
    .input-group-btn
      i.material-icons.prefix type="submit" search
      label for="icon_prefix" Szukaj
      = text_field_tag :query, params[:query], class: "search-query", input_html: {id: 'icon_prefix'}
  .input-field.col-md-3
    .input-group-btn
      i.material-icons.prefix type="submit" search
      label for="icon_prefix" Szukaj po dacie
      = text_field_tag :querydate, params[:querydate], class: "search-query datepicker", input_html: {id: 'icon_prefix'}
  .searchbar-fix
    = submit_tag 'Szukaj', class: 'btn btn-primary'

app/views/shared/_people_searchbar.html.slim
= form_tag search_backend_people_path, method: :get do
  .input-field.col-md-6
    .input-group-btn
      i.material-icons.prefix{type="submit"} search
      label{for="icon_prefix"} Szukaj
      = text_field_tag :query, params[:query], class: "search-query", input_html: {id: 'icon_prefix'}
  .input-field.col-md-3
    .input-group-btn
      i.material-icons.prefix{type="submit"} search
      label{for="icon_prefix"} Szukaj po dacie
      = text_field_tag :querydate, params[:querydate], class: "search-query datepicker", input_html: {id: 'icon_prefix'}
  .searchbar-fix
    = submit_tag 'Szukaj', class: 'btn btn-primary'

app/views/shared/_v_searchbar.html.slim
= form_tag search_backend_vacations_path, method: :get do
  .input-field.col-md-6
    .input-group-btn
      i.material-icons.prefix{type="submit"} search
      label{for="icon_prefix"} Szukaj
      = text_field_tag :query, params[:query], class: "search-query", input_html: {id: 'icon_prefix'}
  .input-field.col-md-3
    .input-group-btn
      i.material-icons.prefix{type="submit"} search
      label{for="icon_prefix"} Szukaj po dacie
      = text_field_tag :querydate, params[:querydate], class: "search-query datepicker", input_html: {id: 'icon_prefix'}
  .searchbar-fix
    = submit_tag 'Szukaj', class: 'btn btn-primary'

app/views/shared/_w_ch_searchbar.html.slim
= form_tag search_backend_work_schedules_path, method: :get do
  .input-field.col-md-6
    .input-group-btn
      i.material-icons.prefix{type="submit"} search
      label{for="icon_prefix"} Szukaj
      = text_field_tag :query, params[:query], class: "search-query", input_html: {id: 'icon_prefix'}
  .searchbar-fix
    = submit_tag 'Szukaj', class: 'btn btn-primary'