config/routes.rb
Rails.application.routes.draw do
  devise_for :people, controllers: { sessions: 'devise/sessions' },
                      skip: [:registrations]
  devise_for :clients, skip: :sessions,
                       controllers: { registrations: 'client/registrations' }

  resources 'contacts', only: [:new, :create]
  root 'home#index'

  namespace :backend do
    root 'news#index'

    resources :products
    devise_for :people, :manager, :receptionists, :lifeguards, :trainers,
               skip: :sessions,
               controllers: { registrations: 'backend/registrations' }

    resources :entry_types do
      resources :bought_details, except: [:show, :edit, :update]
      collection do
        get 'bought_list', to: 'entry_types#show'
        get 'search'
      end
    end
    get 'trainers', to: 'people#trainers'

    resources :activities_people, except: [:show, :new, :edit]
    resources :news do
      member do
        post 'like'
      end
      resources :comments, only: [:create, :edit, :update, :destroy]
    end
    resources :work_schedules do
      collection do
        get 'search'
      end
    end
    resources :activities, except: [:show] do
      collection do
        get 'search'
        get 'pool_zone'
        get 'requests'
      end
      member do
        get 'sign_up'
        get 'preview'
        post 'activate'
        post 'deactivate'
      end
    end

    resources :vacations, only: [] do
      collection do
        get 'requests'
        get 'search'
      end
      member do
        post 'accept'
      end
    end

    resources :manage_trainings, only: [:index, :new, :create]
    # Manage vacations
    resources :manage_vacations, only: :index
    resources :individual_trainings, only: [:index, :update, :show, :edit, :search, :destroy] do
      collection do
        get 'search'
      end
    end
    resources :training_costs, except: [:show]
    resources :people, except: [:new, :create] do
      collection do
        get 'search'
      end

      member do
        delete 'remove_photo'
        get 'bought_history'

        resources :individual_trainings, only: [:update, :choose_trainer] do
          collection do
            get 'choose_trainer'
            get 'show', as: 'show'
            get 'show_details'
          end
        end

        resources :trainers, only: [] do
          resources :individual_trainings, param: :ind_training_id
        end
        resources :work_schedules, as: 'manage_schedule' do
          collection do
            get 'new', as: 'new'
            get 'my_schedule', to: 'work_schedules#show', as: 'my'
          end
        end
        resources :vacations, param: :vacation_id, except: [:show]
      end
    end
    resources :statistics, only: [:index]
    # /das/dsa/users?kind=client|manager|
    [:managers, :clients, :receptionists, :lifeguards].each do |type|
      get type, to: 'people#' + type.to_s
    end
  end
end

app/controllers/backend/activities_controller.rb
class Backend::ActivitiesController < BackendController
  helper_method :sort_column, :sort_direction
  before_action :set_activity, only: [:edit, :update, :destroy, :sign_up,
                                      :preview, :activate, :deactivate]
  before_action :set_trainers
  before_action :set_person, only: :sign_up
  before_action :set_zone, only: :pool_zone
  before_action :set_rule_to_manage, only: [:edit, :update, :destroy, :activate,
                                            :deactivate]
  # GET backend/activities
  def index
    @activities = Activity.includes(:person)
                          .order(sort_column + ' ' + sort_direction)
                          .references(:people)
                          .paginate(page: params[:page], per_page: 20)
    @actual_activities = Activity.includes(:person)
                                 .order(sort_column + ' ' + sort_direction)
                                 .references(:people)
                                 .where('active = ?', true)
                                 .paginate(page: params[:page], per_page: 20)
    @active_activities = ActivitiesPerson.includes(:person)
                                         .order(
                                         sort_column + ' ' + sort_direction)
                                         .references(:people)
                                         .where('activity.active = ?', true)
                                         .paginate(page: params[:page],
                                                   per_page: 20)
  end

  # GET backend/activities/new
  def new
    @activity = Activity.new
  end

  # POST backend/activities
  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      redirect_to backend_activities_path, notice: 'Pomyślnie dodano.'
    else
      render :new
    end
  end

  # GET backend/activities/:id/edit
  def edit
  end

  # PATCH/PUT backend/activities/1
  def update
    if @activity.update(activity_params)
      redirect_to backend_activities_path,
                  notice: 'Pomyślnie zaktualizowano.'
    else
      render :edit
    end
  end

  # POST backend/activities/:id/activate
  def activate
    @activity.update!(active: true)
    redirect_to :back, notice: 'Aktywowano.'
  end

  # POST backend/activities/:id/deactivate
  def deactivate
    @activity.update!(active: false)
    @activities_people = ActivitiesPerson.where(activity_id: @activity)
                                         .where('date >= ?', Date.today)
    @activities_people.each(&:destroy)
    redirect_to :back, notice: 'Deaktywowano.'
  end

  # GET backend/activities/requests
  def requests
    @activity_requests = Activity.includes(:person)
                                 .where(active: false)
                                 .order(sort_column + ' ' + sort_direction)
                                 .references(:people)
                                 .paginate(page: params[:page], per_page: 20)
  end

  # GET backend/activities/pool_zone
  def pool_zone
    @activities_people = Activity.where(activities: { pool_zone: @zone,
                                                      active: true })
                                 .order(start_on: :asc)
    @act_people = ActivitiesPerson.where(activity_id: :activity_id)
                                  .includes(:activity)
                                  .includes(:activities_people)
  end

  # DELETE backend/activities/1
  def destroy
    @activity.destroy
    @activities_people = ActivitiesPerson.where(activity_id: @activity)
    @activities_people.each(&:destroy)
    redirect_to :back, notice: 'Pomyślnie usunięto.'
  end

  # GET backend/activities/:id/preview
  def preview
    @activities_people = @activity.activities_people
                                  .select(:activity_id, :date)
                                  .where('date >= ?', Date.today)
                                  .order(:date)
                                  .distinct
  end

  # GET backend/activities/search
  def search
    if params[:query].present?
      @activities = Activity.text_search(params[:query])
                            .paginate(page: params[:page],
                                      per_page: 20)
    end
  end

  # GET backend/activities/:id/sign_up
  def sign_up
    @activities_person = ActivitiesPerson.new
    @activities_people = ActivitiesPerson.where('activity_id = ?', @activity.id)
                                         .where('person_id = ?', @person.id)
  end

  private

  def activity_params
    params.require(:activity)
          .permit(:name, :description, :active, :day_of_week, :start_on,
                  :end_on, :pool_zone, :max_people, :person_id,
                  activities_people: [:date])
  end

  JOINED_TABLE_COLUMNS = %w(people.first_name).freeze
  def sort_column
    if JOINED_TABLE_COLUMNS.include?(params[:sort]) ||
       Activity.column_names.include?(params[:sort])
      params[:sort]
    else
      'name'
    end
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def set_activity
    @activity = Activity.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:danger] = 'Nie ma aktywności o takim id.'
    redirect_to backend_news_index_path
  end

  def set_zone
    @zone = params[:zone]
  end

  def set_trainers
    @trainers = Trainer.order(:first_name, :last_name)
  end

  def set_person
    @person = current_person
  end

  def set_rule_to_manage
    unless current_manager || current_receptionist
      flash[:danger] = 'Brak dostępu. {set_rule_to_manage}'
      redirect_to backend_news_path
    end
  end
end

app/controllers/backend/activities_people_controller.rb
class Backend::ActivitiesPeopleController < BackendController
 before_action :set_activities_person, only: [:update, :destroy]
  def index
    @activities_people = ActivitiesPerson.all
  end
  def create
    @activities_person = ActivitiesPerson.new(activities_person_params)
    # raise 'Dupa'
    if @activities_person.save
      flash[:notice] = 'Pomyślnie dodano.'
      redirect_to :back
    else
      flash[:danger] = "#{@activities_person.errors.full_messages.join('')}"
      redirect_to :back
    end
  end

  def update
    if @activities_person.update(activities_person_params)
      redirect_to :back, notice: 'Pomyślnie zaktualizowano.'
    else
      render :edit
    end
  end
  def destroy
    @activities_person.destroy
    redirect_to :back, notice: 'Pomyślnie zrezygnowano'
  end

  private

  def set_activities_person
    begin
      @activities_person = ActivitiesPerson.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      flash[:danger] = 'Nie istnieje aktywność o takim id.'
      redirect_to backend_news_index_path
    end
  end
  def activities_person_params
    params.require(:activities_person).permit(:date, :person_id, :activity_id)
  end
end

app/controllers/backend/bought_details_controller.rb
class Backend::BoughtDetailsController < BackendController
  helper_method :sort_bought, :sort_direction
  before_action :set_entry_type, only: [:index, :new, :create]
  before_action :set_bought_detail,
                only: [:edit, :destroy, :activate, :deactivate]
  before_action :set_rule_to_display_bought_details, only: [:index]
  # GET backend/bought_details
  # GET backend/bought_details.json
  def index
    @bought_details = BoughtDetail.includes(:person)
                                  .order(sort_bought + ' ' + sort_direction)
                                  .references(:people)
                                  .where(entry_type_id: @entry_type)
                                  .paginate(page: params[:page], per_page: 20)
    @last_bought = BoughtDetail.where(entry_type_id: @entry_type)
                               .order('bought_data').last
  end

  # GET backend/bought_details/new
  def new
    @bought_detail = BoughtDetail.new
  end

  def create
    @bought_detail = BoughtDetail.new(bought_detail_params)
    @bought_detail.entry_type = @entry_type
    @bought_detail.person = current_person
    if @bought_detail.entry_type.kind == 'Karnet'
      @bought_detail.cost = @bought_detail.entry_type.price *
                            (@bought_detail.days.to_i / 30).floor
    else
      @bought_detail.cost = @bought_detail.entry_type.price
    end

    Stripe.api_key = ENV['STRIPE_SECRET_KEY']
    token = params[:stripeToken]

    begin
      charge = Stripe::Charge.create(
        amount: (@bought_detail.cost * 100).floor,
        currency: 'pln',
        card: token
      )

    rescue Stripe::CardError => e
      @bought_detail.destroy
      flash[:danger] = e.message
      render :new
    end

    if @bought_detail.save
      flash[:notice] = "Dziękujemy za zakup!"
      redirect_to bought_history_backend_person_path(current_person),
                  notice: flash[:notice]
    else
      flash[:danger] = @bought_detail.errors.full_messages
      charge = nil
      Stripe.api_key = ENV['STRIPE_SECRET_KEY']
      token = params[:stripeToken]
      render :new, notice: flash[:danger]
    end
  end

  # DELETE backend/work_schedules/1
  # DELETE backend/work_schedules/1.json
  def destroy
    @bought_detail.destroy
    redirect_to backend_entry_type_bought_details_path,
                notice: 'Pomyślnie usunięto.'
  end

  private

  def set_entry_type
    @entry_type = EntryType.find(params[:entry_type_id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:danger] = 'Nie istnieje wejściówka o takim id.'
    redirect_to backend_news_index_path
  end

  def set_bought_detail
    @bought_detail = BoughtDetail.find(params[:id])
  end

  JOINED_TABLE_COLUMNS = %w(people.first_name).freeze
  def sort_bought
    if JOINED_TABLE_COLUMNS.include?(params[:sort]) || BoughtDetail.column_names.include?(params[:sort])
      params[:sort]
    else
      'bought_data'
    end
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
  end

  # only allow the white list through.
  def bought_detail_params
    params.require(:bought_detail).permit(:bought_data, :start_on, :end_on,
                                          :entry_type_id, :days, :person_id,
                                          :credit_card, :card_code)
  end

  def set_rule_to_display_bought_details
    unless current_manager || current_receptionist
      flash[:danger] = 'Brak dostępu.'
      redirect_to backend_news_index_path
    end
  end
end

app/controllers/backend/clients_controller.rb
class Backend::ClientsController < BackendController
end

app/controllers/backend/comments_controller.rb
class Backend::CommentsController < BackendController
  before_action :require_same_user, only: [:edit, :update]
  before_action :set_news
  before_action :set_comment, except: :create
  def create
    @comment = @news.comments.build(comment_params)
    @comment.person = current_person
    if @comment.save
      redirect_to backend_news_path(@news),
                  notice: 'Komentarz pomyślnie dodano'
    else
      flash[:danger] = 'Komentarz nie został dodany. Wymagana treść, minimum 5 znaków.'
      redirect_to :back
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      flash[:notice] = 'Komentarz został zaktualizowany!'
      redirect_to backend_news_path(@news)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = 'Komentarz usunięty.'
    redirect_to backend_news_path(@news)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_news
    @news = News.find(params[:news_id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:danger] = 'Nie istnieje news o takim id.'
    redirect_to backend_news_index_path
  end

  def set_comment
    @comment = Comment.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:danger] = 'Nie istnieje komentarz o takim id.'
    redirect_to backend_news_index_path
  end

  def require_same_user
    begin
      @comment = Comment.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      flash[:danger] = 'Nie istnieje komentarz o takim id.'
      redirect_to backend_news_index_path
    end
    unless current_person == @comment.person || current_receptionist || current_manager
      flash[:danger] = 'Możesz edytować tylko własne komentarze.'
      redirect_to backend_news_index_path
    end
  end
end

app/controllers/backend/lifeguards_controller.rb
class Backend::LifeguardsController < BackendController
end

app/controllers/backend/manage_vacations_controller.rb
class Backend::ManageVacationsController < BackendController
  helper_method :sort_column, :sort_direction
  before_action :select_rule_vacations, only: :index
  def index
    @vacations = Vacation.includes(:person).order(sort_column + ' ' + sort_direction).references(:people)
                         .paginate(page: params[:page], per_page: 20)
  end

  private

  def select_rule_vacations
    unless current_manager || current_receptionist
      redirect_to backend_news_index_path, notice: 'Brak dostępu {select_rule_vacations}'
    end
  end
  JOINED_TABLE_COLUMNS = %w(people.first_name).freeze
  def sort_column
    if JOINED_TABLE_COLUMNS.include?(params[:sort]) || Vacation.column_names.include?(params[:sort])
      params[:sort]
    else
      'start_at'
    end
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/controllers/backend/managers_controller.rb
class Backend::ManagersController < BackendController
end

app/controllers/backend/receptionists_controller.rb
class Backend::ReceptionistsController < BackendController
end

app/controllers/backend/registrations_controller.rb
# Controller for backend registration actions by devise gem
class Backend::RegistrationsController < Devise::RegistrationsController
  skip_before_filter :require_no_authentication, only: [:new, :create]
  layout 'backend'
  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    build_resource(sign_up_params)
    if resource.save
      flash[:notice] = 'Pomyślnie zarejestrowano konto pracownika.'
      redirect_to backend_people_path
    else
      flash[:danger] = 'Nie udało się zarejestrować konta.'
      clean_up_passwords resource
      respond_with resource
    end
  end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  private

  def configure_permitted_parameters
    sanitized_params = %i(
      pesel
      first_name
      last_name
      date_of_birth
      profile_image
      salary
      hiredate
      type
      password
      password_confirmation
    )
    devise_parameter_sanitizer.permit(:sign_up, keys: sanitized_params)
    devise_parameter_sanitizer.permit(:account_update, keys: sanitized_params)
  end
end

app/views/backend/individual_trainings/_form.html.slim
- if current_client
  = simple_form_for(@individual_training, url:  backend_trainer_individual_trainings_path) do |f|
    = errors_for(@individual_training)
    .col-md-6
      #stripe_ind_error.alert.alert-danger style="display:none"
      .panel.panel-success
        .panel-heading Dane do płatności
        .panel-body
          .row.input-field
            = f.input :credit_card, input_html: {'data-stripe' => "number"}
          .row.input-field
            = f.input :card_code, input_html: {'data-stripe' => "cvc"}
          .row.input-field
            .col-md-3
              = select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month", :'data-stripe' => "exp-month"}
            .col-md-3
              = select_year nil, {start_year: Date.today.year, end_year: Date.today.year+15}, {name: nil, id: "card_year", :'data-stripe' => "exp-year"}

    .col-md-6
      label for='datepicker'* Data treningu
      = f.text_field :date_of_training, as: :date, class: 'datepicker',
        placeholder: 'Kliknij'
      label for='input_starttime'* Godzina rozpoczęcia
      = f.text_field :start_on, class: 'timepicker', required: true,
        id: 'input_starttime', placeholder: 'Kliknij'
      = f.input :training_cost_id, required: true, label: "Czas trwania" ,
        collection: @training_costs.map{ |tc| [tc.full_duration, tc.id] },
        prompt: 'Wybierz czas trwania treningu'
      = f.input :trainer_id, as: :hidden, input_html: { value: @trainer.id }
      = f.input :client_id, as: :hidden, input_html: { value: @client.id }
      = f.button :submit, class: "btn btn-primary btn-block"

- else
  = simple_form_for(@individual_training, url:  backend_trainer_individual_training_path) do |f|
    = errors_for(@individual_training)
    .col-md-6
      label for='datepicker'* Data treningu
      = f.text_field :date_of_training, as: :date, class: 'datepicker',
        placeholder: 'Kliknij'
      label for='input_starttime'* Godzina rozpoczęcia
      = f.text_field :start_on, class: 'timepicker', required: true,
        id: 'input_starttime', placeholder: 'Kliknij'
      = f.input :training_cost_id, required: true, label: "Czas trwania" ,
        collection: @training_costs.map{ |tc| [tc.full_duration, tc.id] },
        prompt: 'Wybierz czas trwania treningu'
      = f.input :trainer_id, as: :hidden, input_html: { value: @trainer.id }
      = f.input :client_id, as: :hidden, input_html: { value: @client.id }
      = f.button :submit, class: "btn btn-primary btn-block"
javascript:
  var payment;

  var errorMessages = {
      incorrect_number: 'Numer karty jest nieprawidłowy.',
      invalid_number: 'Numer karty nie jest prawidłowy.',
      invalid_expiry_month: 'Termin wygaśnięcia karty jest nieprawidłowy.',
      invalid_expiry_year: 'Rok ważności karty jest nieprawidłowy.',
      invalid_cvc: 'Kod zabezpieczający kartę jest nieprawidłowy.',
      expired_card: 'Karta wygasła.',
      incorrect_cvc: 'Kod CVV jest nieprawidłowy.',
      incorrect_zip: 'Kod pocztowy karty jest nieprawidłowy.',
      card_declined: 'Karta została odrzucona.',
      missing: 'Nie ma karty na klienta, która jest w trakcie ładowania.',
      processing_error: 'Podczas przetwarzania karty wystąpił błąd.',
      rate_limit: 'Wystąpił błąd z powodu zbyt szybkiego przetwarzania wniosków API. Daj nam znać, jeśli błąd będzie stale występował.'
  };

  jQuery(function() {
      Stripe.setPublishableKey($('meta[name="stripe-key"]').attr('content'));
      return payment.setupForm();
  });

  payment = {
      setupForm: function() {
          return $('#new_individual_training').submit(function() {
              $('input[type=submit]').attr('disabled', true);
              Stripe.card.createToken($('#new_individual_training'), payment.handleStripeResponse);
              return false;
          });
      },
      handleStripeResponse: function (status, response) {
          if (status === 200) {
              $('#new_individual_training').append($('<input type="hidden" name="stripeToken" />').val(response.id));
              return $('#new_individual_training')[0].submit();

          } else {
            if ( response.error && response.error.type == 'card_error'){
              $('#stripe_ind_error').text(errorMessages[response.error.code]).show();
            } else {
              $('#stripe_ind_error').text('Brak danych do płatności').show();
            }
              return $('input[type=submit]').attr('disabled', false);
          }
      }
  };

app/views/backend/individual_trainings/choose_date.html.slim
.col-md-6
  h5
    | Trener
    = @trainer.full_name

  h6
    | Harmonogram pracy:

  .col-md-6
    table.table.table-striped.table-bordered.table-list
      thead
        tr
          th Dzień tygodnia
          th Godzina od
          th Godzina do
      tbody
        - @trainer.work_schedules.each do |tw|
          tr
            td
              = tw.day_of_week
            td
              = l(tw.start_time, format: :short)
            td
              = l(tw.end_time, format: :short)

.col-md-6
  = simple_form_for([:backend, @individual_training]) do |f|
    = errors_for(@individual_training)
    = f.input :day, label: "Dzień tygodnia", collection: @trainer.work_schedules.map{|tw| [tw.day_of_week, tw.id]}, prompt: "Wybierz dzień tygodnia"
    = f.select :duration, [['15 minut', 15], ['30 minut', 30], ['60 minut', 60]],  prompt: 'Wybierz czas treningu', required: true
    = f.input :start_on
    = f.button :submit, class: "btn btn-primary btn-block"

app/views/backend/individual_trainings/choose_trainer.html.slim
h5.section-title.st-blue
  | 1 krok
  small Wybór trenera
h5 Trenerzy
= info("Poniżej znajduje się lista dostępnych trenerów, z którymi możesz \
        przeprowadzić indywidualny trening.")


- @trainers.each do |t|
  .col-md-4
    .testimonial-card.z-depth-1
      .card-up.default-color-dark
      .avatar
        img.img-circle.img-responsive src=t.profile_image
      .card-content
        h5
          = t.full_name
        p
          | Wiek: #{t.age}
        p
          | Dostępny w dni:
          - t.work_schedules.each_with_index do |w, i|
            - if i == t.work_schedules.size - 1
              |  #{w.day_of_week}
            - else
              |  #{w.day_of_week + ', '}
        h5
          = link_to new_backend_trainer_individual_training_path(current_person, t.id) do
            .btn.btn-border-default.waves-effect
              i.fa.fa-check-circle-o
              | Wybieram


= will_paginate @trainers, renderer: BootstrapPagination::Rails

app/views/backend/individual_trainings/edit.html.slim
= link_to backend_individual_trainings_path do
  .btn.btn-primary.waves-effect.waves-light
    i.fa.fa-chevron-left
    |  Wróć
h5 Edycja treningu
= info("Jesteś na stronie edycji szczegółów dot. treningu indywidualnego.")
= render 'form'

app/views/backend/individual_trainings/index.html.slim
h5 Treningi indywidualne klientów.
p
  | Obecnie w bazie posiadamy #{IndividualTraining.count} zarejestrowanych
  |  treningów.
= info("Poniżej znajduje się lista wszystkich zarejestrowanych treningów \
        indywidualnych odbytych lub zaplanowanych w najbliższym czasie.")

- if current_manager
  = link_to new_backend_manage_training_path(@person), class: 'btn btn-primary' do
    i.fa.fa-plus
    |  Dodaj trening
= render 'shared/it_searchbar'
table.table.table-striped.table-bordered.table-list.pretty.table-list-search
  thead
    tr
      th
        em.fa.fa-cog
        |  Zarządzanie
      th
        = sortable "training_costs.cost", "Koszt"
      th
        = sortable "clients.first_name", "Klient"
      th
        = sortable "people.first_name", "Trener"
      th
        = sortable "date_of_training", "Data"
      th
        = sortable "start_on", "Godzina rozpoczęcia"
      th
        = sortable "end_on", "Godzina zakończenia"
      th
        = sortable "training_costs.duration", "Czas trwania"
  tbody
    - @individual_trainings.each do |training|
      tr
        td
          = link_to edit_backend_trainer_individual_training_path(training.client, training.trainer, training) do
            i.btn.btn-default
              i.fa.fa-pencil
          = link_to backend_individual_training_path(training), method: :delete, data: { confirm: 'Jesteś pewny/a?' } do
            i.btn.btn-danger
              i.fa.fa-trash
        td
          - unless training.training_cost.blank?
            = empty_info(training.training_cost.cost.nice, "--BRAK DANYCH--")
            |  zł
          - else
            = empty_info(training.training_cost, "--BRAK DANYCH--")
        td
          = link_to backend_person_path(training.client) do
            = training.client.full_name
        td
          = link_to backend_person_path(training.trainer) do
            = training.trainer.full_name
        td
          = l(training.date_of_training)
        td
          = l(training.start_on, format: :short)
        td
          = l(training.end_on, format: :short)
        td
          - unless training.training_cost.blank?
            = training.training_cost.duration
            |  min.
          - else
            = empty_info(training.training_cost, "--BRAK DANYCH--")
= will_paginate @individual_trainings, renderer: BootstrapPagination::Rails unless @individual_trainings.blank?

app/views/backend/individual_trainings/search.html.slim
= link_to backend_individual_trainings_path do
  .btn.btn-primary.waves-effect.waves-light
    i.fa.fa-chevron-left
    |  Wróć
h5 Rezultat wyszukiwania
= info("Poniżej znajdują się wyniki Twojego wyszukiwania odnośnie treningów \
        indywidualnych.")
= render 'shared/it_searchbar'
table.table.table-striped.table-bordered.table-list.pretty.table-list-search
  thead
    tr
      th
        em.fa.fa-cog
        |  Zarządzanie
      th
        | Koszt
      th
        | Klient
      th
        | Trener
      th
        | Data
      th
        | Godzina rozpoczęcia
      th
        | Godzina zakończenia
      th
        | Czas trwania
  tbody
    - unless @individual_trainings.blank?
      - @individual_trainings.each do |training|
        tr
          td
            = link_to edit_backend_individual_training_path(training) do
              i.btn.btn-default
                i.fa.fa-pencil
            = link_to backend_individual_training_path(training), method: :delete, data: { confirm: 'Jesteś pewny/a?' } do
              i.btn.btn-danger
                i.fa.fa-trash
          td
            = training.training_cost.cost.nice
            |  zł
          td
            = training.client.try(:full_name)
          td
            = training.trainer.try(:full_name)
          td
            = l(training.date_of_training)
          td
            = l(training.start_on, format: :short)
          td
            = l(training.end_on, format: :short)
          td
            = training.training_cost.duration
            |  min.
      = will_paginate @individual_trainings, renderer: BootstrapPagination::Rails unless @individual_trainings.blank?
    - else
      tr
        td colspan='8'
          .text-center
            | Brak rezultatów.

app/views/backend/individual_trainings/show.html.slim
h5 Moje treningi indywidualne
= info("Jesteś na stronie wszystkich zarejestrowanych treningów indywidualnych \
        dotyczących Ciebie.")
- if @person.type == 'Client'
  .row
    .col-md-6
      - unless @nearest_training.blank?
        ul.collection
          li.collection-item
            h5 Najbliższy trening:
          li.collection-item
            - if @days > 1
              p
                | Już za #{@days} dni!
            - elsif @days == 1
              p
                |  Już jutro!
            - elsif @days == 0
              p
                |  Już dziś!
          li.collection-item
            p
              | Data: #{l(@nearest_training.date_of_training)}
            p
              | Godzina: #{l(@nearest_training.start_on, format: :short)}
              br
              | Czas trwania:
              |  #{@nearest_training.training_cost.duration}
              |  min.
  = month_calendar attribute: :date_of_training, events: @individual_trainings do |date_of_training, trainings|
    = date_of_training.strftime("%d")
    br
    - trainings.each_with_index do |training, index|
      - if index < 3
        | #{l(training.start_on, format: :short)} - #{l(training.end_on, format: :short)}
        |  #{training.trainer.full_name}
        br
        - if index == 2
          = link_to show_details_backend_individual_trainings_path(@person, date_of_training: training.date_of_training) do
            .btn.btn-warning.btn-xs
              | Więcej
  br

- elsif @person.type == 'Trainer'
  = month_calendar attribute: :date_of_training, events: @trainer_individual_trainings do |date_of_training, trainings|
    = date_of_training.strftime("%d")
    br
    - trainings.each_with_index do |training, index|
      - if index < 3
        | #{l(training.start_on, format: :short)} - #{l(training.end_on, format: :short)}
        |  #{training.trainer.full_name}
        br
        - if index == 2
          = link_to show_details_backend_individual_trainings_path(@person, date_of_training: training.date_of_training) do
            .btn.btn-warning.btn-xs
              | Więcej
    br