config/routes.rb
Rails.application.routes.draw do
  devise_for :people, controllers: { sessions: 'devise/sessions' },
                      skip: [:registrations]
  devise_for :clients, skip: :sessions,
                       controllers: { registrations: 'client/registrations' }

  resources 'contacts', only: [:new, :create]
  root 'home#index'

  namespace :backend do
    root 'news#index'

    resources :products
    devise_for :people, :manager, :receptionists, :lifeguards, :trainers,
               skip: :sessions,
               controllers: { registrations: 'backend/registrations' }

    resources :entry_types do
      resources :bought_details, except: [:show, :edit, :update]
      collection do
        get 'bought_list', to: 'entry_types#show'
        get 'search'
      end
    end
    get 'trainers', to: 'people#trainers'

    resources :activities_people, except: [:show, :new, :edit]
    resources :news do
      member do
        post 'like'
      end
      resources :comments, only: [:create, :edit, :update, :destroy]
    end
    resources :work_schedules do
      collection do
        get 'search'
      end
    end
    resources :activities, except: [:show] do
      collection do
        get 'search'
        get 'pool_zone'
        get 'requests'
      end
      member do
        get 'sign_up'
        get 'preview'
        post 'activate'
        post 'deactivate'
      end
    end

    resources :vacations, only: [] do
      collection do
        get 'requests'
        get 'search'
      end
      member do
        post 'accept'
      end
    end

    resources :manage_trainings, only: [:index, :new, :create]
    # Manage vacations
    resources :manage_vacations, only: :index
    resources :individual_trainings, only: [:index, :update, :show, :edit, :search, :destroy] do
      collection do
        get 'search'
      end
    end
    resources :training_costs, except: [:show]
    resources :people, except: [:new, :create] do
      collection do
        get 'search'
      end

      member do
        delete 'remove_photo'
        get 'bought_history'

        resources :individual_trainings, only: [:update, :choose_trainer] do
          collection do
            get 'choose_trainer'
            get 'show', as: 'show'
            get 'show_details'
          end
        end

        resources :trainers, only: [] do
          resources :individual_trainings, param: :ind_training_id
        end
        resources :work_schedules, as: 'manage_schedule' do
          collection do
            get 'new', as: 'new'
            get 'my_schedule', to: 'work_schedules#show', as: 'my'
          end
        end
        resources :vacations, param: :vacation_id, except: [:show]
      end
    end
    resources :statistics, only: [:index]
    # /das/dsa/users?kind=client|manager|
    [:managers, :clients, :receptionists, :lifeguards].each do |type|
      get type, to: 'people#' + type.to_s
    end
  end
end

app/controllers/backend/activities_controller.rb
class Backend::ActivitiesController < BackendController
  helper_method :sort_column, :sort_direction
  before_action :set_activity, only: [:edit, :update, :destroy, :sign_up,
                                      :preview, :activate, :deactivate]
  before_action :set_trainers
  before_action :set_person, only: :sign_up
  before_action :set_zone, only: :pool_zone
  before_action :set_rule_to_manage, only: [:edit, :update, :destroy, :activate,
                                            :deactivate]
  # GET backend/activities
  def index
    @activities = Activity.includes(:person)
                          .order(sort_column + ' ' + sort_direction)
                          .references(:people)
                          .paginate(page: params[:page], per_page: 20)
    @actual_activities = Activity.includes(:person)
                                 .order(sort_column + ' ' + sort_direction)
                                 .references(:people)
                                 .where('active = ?', true)
                                 .paginate(page: params[:page], per_page: 20)
    @active_activities = ActivitiesPerson.includes(:person)
                                         .order(
                                         sort_column + ' ' + sort_direction)
                                         .references(:people)
                                         .where('activity.active = ?', true)
                                         .paginate(page: params[:page],
                                                   per_page: 20)
  end

  # GET backend/activities/new
  def new
    @activity = Activity.new
  end

  # POST backend/activities
  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      redirect_to backend_activities_path, notice: 'Pomyślnie dodano.'
    else
      render :new
    end
  end

  # GET backend/activities/:id/edit
  def edit
  end

  # PATCH/PUT backend/activities/1
  def update
    if @activity.update(activity_params)
      redirect_to backend_activities_path,
                  notice: 'Pomyślnie zaktualizowano.'
    else
      render :edit
    end
  end

  # POST backend/activities/:id/activate
  def activate
    @activity.update!(active: true)
    redirect_to :back, notice: 'Aktywowano.'
  end

  # POST backend/activities/:id/deactivate
  def deactivate
    @activity.update!(active: false)
    @activities_people = ActivitiesPerson.where(activity_id: @activity)
                                         .where('date >= ?', Date.today)
    @activities_people.each(&:destroy)
    redirect_to :back, notice: 'Deaktywowano.'
  end

  # GET backend/activities/requests
  def requests
    @activity_requests = Activity.includes(:person)
                                 .where(active: false)
                                 .order(sort_column + ' ' + sort_direction)
                                 .references(:people)
                                 .paginate(page: params[:page], per_page: 20)
  end

  # GET backend/activities/pool_zone
  def pool_zone
    @activities_people = Activity.where(activities: { pool_zone: @zone,
                                                      active: true })
                                 .order(start_on: :asc)
    @act_people = ActivitiesPerson.where(activity_id: :activity_id)
                                  .includes(:activity)
                                  .includes(:activities_people)
  end

  # DELETE backend/activities/1
  def destroy
    @activity.destroy
    @activities_people = ActivitiesPerson.where(activity_id: @activity)
    @activities_people.each(&:destroy)
    redirect_to :back, notice: 'Pomyślnie usunięto.'
  end

  # GET backend/activities/:id/preview
  def preview
    @activities_people = @activity.activities_people
                                  .select(:activity_id, :date)
                                  .where('date >= ?', Date.today)
                                  .order(:date)
                                  .distinct
  end

  # GET backend/activities/search
  def search
    if params[:query].present?
      @activities = Activity.text_search(params[:query])
                            .paginate(page: params[:page],
                                      per_page: 20)
    end
  end

  # GET backend/activities/:id/sign_up
  def sign_up
    @activities_person = ActivitiesPerson.new
    @activities_people = ActivitiesPerson.where('activity_id = ?', @activity.id)
                                         .where('person_id = ?', @person.id)
  end

  private

  def activity_params
    params.require(:activity)
          .permit(:name, :description, :active, :day_of_week, :start_on,
                  :end_on, :pool_zone, :max_people, :person_id,
                  activities_people: [:date])
  end

  JOINED_TABLE_COLUMNS = %w(people.first_name).freeze
  def sort_column
    if JOINED_TABLE_COLUMNS.include?(params[:sort]) ||
       Activity.column_names.include?(params[:sort])
      params[:sort]
    else
      'name'
    end
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def set_activity
    @activity = Activity.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:danger] = 'Nie ma aktywności o takim id.'
    redirect_to backend_news_index_path
  end

  def set_zone
    @zone = params[:zone]
  end

  def set_trainers
    @trainers = Trainer.order(:first_name, :last_name)
  end

  def set_person
    @person = current_person
  end

  def set_rule_to_manage
    unless current_manager || current_receptionist
      flash[:danger] = 'Brak dostępu. {set_rule_to_manage}'
      redirect_to backend_news_path
    end
  end
end

app/controllers/backend/activities_people_controller.rb
class Backend::ActivitiesPeopleController < BackendController
 before_action :set_activities_person, only: [:update, :destroy]
  def index
    @activities_people = ActivitiesPerson.all
  end
  def create
    @activities_person = ActivitiesPerson.new(activities_person_params)
    # raise 'Dupa'
    if @activities_person.save
      flash[:notice] = 'Pomyślnie dodano.'
      redirect_to :back
    else
      flash[:danger] = "#{@activities_person.errors.full_messages.join('')}"
      redirect_to :back
    end
  end

  def update
    if @activities_person.update(activities_person_params)
      redirect_to :back, notice: 'Pomyślnie zaktualizowano.'
    else
      render :edit
    end
  end
  def destroy
    @activities_person.destroy
    redirect_to :back, notice: 'Pomyślnie zrezygnowano'
  end

  private

  def set_activities_person
    begin
      @activities_person = ActivitiesPerson.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      flash[:danger] = 'Nie istnieje aktywność o takim id.'
      redirect_to backend_news_index_path
    end
  end
  def activities_person_params
    params.require(:activities_person).permit(:date, :person_id, :activity_id)
  end
end

app/controllers/backend/bought_details_controller.rb
class Backend::BoughtDetailsController < BackendController
  helper_method :sort_bought, :sort_direction
  before_action :set_entry_type, only: [:index, :new, :create]
  before_action :set_bought_detail,
                only: [:edit, :destroy, :activate, :deactivate]
  before_action :set_rule_to_display_bought_details, only: [:index]
  # GET backend/bought_details
  # GET backend/bought_details.json
  def index
    @bought_details = BoughtDetail.includes(:person)
                                  .order(sort_bought + ' ' + sort_direction)
                                  .references(:people)
                                  .where(entry_type_id: @entry_type)
                                  .paginate(page: params[:page], per_page: 20)
    @last_bought = BoughtDetail.where(entry_type_id: @entry_type)
                               .order('bought_data').last
  end

  # GET backend/bought_details/new
  def new
    @bought_detail = BoughtDetail.new
  end

  def create
    @bought_detail = BoughtDetail.new(bought_detail_params)
    @bought_detail.entry_type = @entry_type
    @bought_detail.person = current_person
    if @bought_detail.entry_type.kind == 'Karnet'
      @bought_detail.cost = @bought_detail.entry_type.price *
                            (@bought_detail.days.to_i / 30).floor
    else
      @bought_detail.cost = @bought_detail.entry_type.price
    end

    Stripe.api_key = ENV['STRIPE_SECRET_KEY']
    token = params[:stripeToken]

    begin
      charge = Stripe::Charge.create(
        amount: (@bought_detail.cost * 100).floor,
        currency: 'pln',
        card: token
      )

    rescue Stripe::CardError => e
      @bought_detail.destroy
      flash[:danger] = e.message
      render :new
    end

    if @bought_detail.save
      flash[:notice] = "Dziękujemy za zakup!"
      redirect_to bought_history_backend_person_path(current_person),
                  notice: flash[:notice]
    else
      flash[:danger] = @bought_detail.errors.full_messages
      charge = nil
      Stripe.api_key = ENV['STRIPE_SECRET_KEY']
      token = params[:stripeToken]
      render :new, notice: flash[:danger]
    end
  end

  # DELETE backend/work_schedules/1
  # DELETE backend/work_schedules/1.json
  def destroy
    @bought_detail.destroy
    redirect_to backend_entry_type_bought_details_path,
                notice: 'Pomyślnie usunięto.'
  end

  private

  def set_entry_type
    @entry_type = EntryType.find(params[:entry_type_id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:danger] = 'Nie istnieje wejściówka o takim id.'
    redirect_to backend_news_index_path
  end

  def set_bought_detail
    @bought_detail = BoughtDetail.find(params[:id])
  end

  JOINED_TABLE_COLUMNS = %w(people.first_name).freeze
  def sort_bought
    if JOINED_TABLE_COLUMNS.include?(params[:sort]) || BoughtDetail.column_names.include?(params[:sort])
      params[:sort]
    else
      'bought_data'
    end
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
  end

  # only allow the white list through.
  def bought_detail_params
    params.require(:bought_detail).permit(:bought_data, :start_on, :end_on,
                                          :entry_type_id, :days, :person_id,
                                          :credit_card, :card_code)
  end

  def set_rule_to_display_bought_details
    unless current_manager || current_receptionist
      flash[:danger] = 'Brak dostępu.'
      redirect_to backend_news_index_path
    end
  end
end

app/controllers/backend/clients_controller.rb
class Backend::ClientsController < BackendController
end

app/controllers/backend/comments_controller.rb
class Backend::CommentsController < BackendController
  before_action :require_same_user, only: [:edit, :update]
  before_action :set_news
  before_action :set_comment, except: :create
  def create
    @comment = @news.comments.build(comment_params)
    @comment.person = current_person
    if @comment.save
      redirect_to backend_news_path(@news),
                  notice: 'Komentarz pomyślnie dodano'
    else
      flash[:danger] = 'Komentarz nie został dodany. Wymagana treść, minimum 5 znaków.'
      redirect_to :back
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      flash[:notice] = 'Komentarz został zaktualizowany!'
      redirect_to backend_news_path(@news)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = 'Komentarz usunięty.'
    redirect_to backend_news_path(@news)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_news
    @news = News.find(params[:news_id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:danger] = 'Nie istnieje news o takim id.'
    redirect_to backend_news_index_path
  end

  def set_comment
    @comment = Comment.find(params[:id])
  rescue ActiveRecord::RecordNotFound => e
    flash[:danger] = 'Nie istnieje komentarz o takim id.'
    redirect_to backend_news_index_path
  end

  def require_same_user
    begin
      @comment = Comment.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      flash[:danger] = 'Nie istnieje komentarz o takim id.'
      redirect_to backend_news_index_path
    end
    unless current_person == @comment.person || current_receptionist || current_manager
      flash[:danger] = 'Możesz edytować tylko własne komentarze.'
      redirect_to backend_news_index_path
    end
  end
end

app/controllers/backend/lifeguards_controller.rb
class Backend::LifeguardsController < BackendController
end

app/controllers/backend/manage_vacations_controller.rb
class Backend::ManageVacationsController < BackendController
  helper_method :sort_column, :sort_direction
  before_action :select_rule_vacations, only: :index
  def index
    @vacations = Vacation.includes(:person).order(sort_column + ' ' + sort_direction).references(:people)
                         .paginate(page: params[:page], per_page: 20)
  end

  private

  def select_rule_vacations
    unless current_manager || current_receptionist
      redirect_to backend_news_index_path, notice: 'Brak dostępu {select_rule_vacations}'
    end
  end
  JOINED_TABLE_COLUMNS = %w(people.first_name).freeze
  def sort_column
    if JOINED_TABLE_COLUMNS.include?(params[:sort]) || Vacation.column_names.include?(params[:sort])
      params[:sort]
    else
      'start_at'
    end
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/controllers/backend/managers_controller.rb
class Backend::ManagersController < BackendController
end

app/controllers/backend/receptionists_controller.rb
class Backend::ReceptionistsController < BackendController
end

app/controllers/backend/registrations_controller.rb
# Controller for backend registration actions by devise gem
class Backend::RegistrationsController < Devise::RegistrationsController
  skip_before_filter :require_no_authentication, only: [:new, :create]
  layout 'backend'
  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    build_resource(sign_up_params)
    if resource.save
      flash[:notice] = 'Pomyślnie zarejestrowano konto pracownika.'
      redirect_to backend_people_path
    else
      flash[:danger] = 'Nie udało się zarejestrować konta.'
      clean_up_passwords resource
      respond_with resource
    end
  end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  private

  def configure_permitted_parameters
    sanitized_params = %i(
      pesel
      first_name
      last_name
      date_of_birth
      profile_image
      salary
      hiredate
      type
      password
      password_confirmation
    )
    devise_parameter_sanitizer.permit(:sign_up, keys: sanitized_params)
    devise_parameter_sanitizer.permit(:account_update, keys: sanitized_params)
  end
end

app/views/backend/activities/_form.html.slim
= simple_form_for([:backend, @activity]) do |f|
  = errors_for(@activity)
  .row
    .input-field
      = f.input :name
    .input-field
      = f.input :description, input_html: {class:'materialize-textarea'}
    - if current_manager || current_receptionist
      .checkbox-fix
        = f.input :active
    - else
      = f.input :active, as: :hidden, input_html: { value: false}
    .col-md-6
      .form-group
        label for='input_starttime'* Czas rozpoczęcia
        = f.text_field :start_on, class: 'timepicker',
          id: 'input_starttime', id: 'input_starttime', placeholder: 'Kliknij'
    .col-md-6
      .form-group
        label for='input_endtime'* Czas zakończenia
        = f.text_field :end_on, class: 'timepicker', id: 'input_endtime',
          required: true, placeholder: 'Kliknij'
    .form-group
      = f.input :day_of_week, as: :select, collection: Activity::DAYS,
                              prompt: "Wybierz dzień tygodnia"
    .form-group
      = f.input :pool_zone, collection: [['A', 'A'], ['B', 'B'], ['C', 'C'],
      ['D', 'D'], ['E', 'E'], ['F', 'F']], prompt: 'Wybierz strefę'
    - unless current_trainer
      .form-group
        = f.input :person_id, collection: @trainers.map{|t| [t.full_name, t.id]},
                              prompt: "Wybierz trenera"
    - else
      = f.input :person_id, as: :hidden, input_html: { value: current_trainer.id}
    .input-field
      = f.input :max_people
    = f.button :submit, class: "btn btn-primary btn-block"

app/views/backend/activities/edit.html.slim
= render 'shared/back'
= info("Jesteś na stronie edycji informacji dot. konkretnego zajęcia grupowego.")
h5 Edytowanie zajęcia grupowego

= render 'form'

app/views/backend/activities/index.html.slim
h5 Zajęcia grupowe
- if current_manager || current_receptionist
  p
    = link_to new_backend_activity_path, class: 'btn btn-primary' do
      i.fa.fa-plus
      |  Dodaj zajęcia
= info("Jesteś na stronie prezentującej wszystkie zajęcia odbywające się w \
aquaparku(aktywne) lub te które są na razie nie wdrożone(nieaktywne).")

= render 'shared/a_searchbar'
.row
  table.table.table-striped.table-bordered.table-list.pretty.table-list-search
    thead
      tr
        th
          em.fa.fa-cog
          |  Zarządzanie
        th
          = sortable 'name', 'Nazwa'
        th
          = sortable 'description', 'Opis'
        th
          = sortable 'active', 'Aktywne?'
        th
          = sortable 'day_of_week', 'Dzień tygodnia'
        th
          = sortable 'start_on', 'Godzina rozpoczęcia'
        th
          = sortable 'end_on', 'Godzina zakończenia'
        th
          = sortable 'pool_zone', 'Strefa basenu'
        th
          = sortable 'people.first_name', 'Trener'
        th
          = sortable 'max_people', 'Maksymalna ilość osób'
    tbody
      -unless current_client
        - @activities.each do |activity|
          tr
            td
              - if current_receptionist || current_manager
                = link_to edit_backend_activity_path(activity), title: 'Edytuj' do
                  .btn.btn-default
                    i.fa.fa-pencil
                = link_to backend_activity_path(activity), title: 'Usuń', method: :delete, data: {confirm: 'Jesteś pewny/a?'} do
                  .btn.btn-danger
                    i.fa.fa-trash
                - if activity.active
                  - if current_receptionist || current_manager
                    = link_to deactivate_backend_activity_path(activity), title: 'Deaktywuj', method: :post do
                      .btn.btn-danger
                        i.fa.fa-calendar-minus-o
                - unless activity.active
                  = link_to activate_backend_activity_path(activity), title: 'Aktywuj', method: :post do
                    .btn.btn-success
                      i.fa.fa-calendar-plus-o
              - if current_client
                = link_to sign_up_backend_activity_path(activity), title: 'Dołącz' do
                  .btn.btn-success
                    i.fa.fa-user-plus
              = link_to preview_backend_activity_path(activity), title: 'Lista uczestników' do
                i.btn.btn-warning
                  i.fa.fa-search
            td
              = activity.name
            td
              = empty_info(activity.description, "--BRAK OPISU--")
            td
              = show_status(activity.active)
            td
              = activity.day_of_week
            td
              = l(activity.start_on, format: :short)
            td
              = l(activity.end_on, format: :short)
            td
              = link_to pool_zone_backend_activities_path(zone: activity.pool_zone) do
                .btn.btn-warning
                  = activity.pool_zone
            td
              = link_to backend_person_path(activity.person) do
                = activity.person.full_name
            td
              = empty_info(activity.max_people, "--BRAK OGRANICZENIA--")
      - else
        - @actual_activities.each do |activity|
          tr
            td
              - if current_receptionist || current_manager
                = link_to edit_backend_activity_path(activity), title: 'Edytuj' do
                  i.btn.btn-default
                    i.fa.fa-pencil
                = link_to backend_activity_path(activity), title: 'Usuń', method: :delete, data: {confirm: 'Jesteś pewny/a?'} do
                  i.btn.btn-danger
                    i.fa.fa-trash
                - if activity.active
                  - if current_receptionist || current_manager
                    = link_to deactivate_backend_activity_path(activity, active: false), title: 'Deaktywuj', method: :post do
                      i.btn.btn-danger
                        i.fa.fa-calendar-minus-o
                - unless activity.active
                  = link_to activate_backend_activity_path(activity, active: true), title: 'Aktywuj', method: :post do
                    i.btn.btn-success
                      i.fa.fa-calendar-plus-o
              = link_to sign_up_backend_activity_path(activity), title: 'Dołącz' do
                i.btn.btn-success
                  i.fa.fa-user-plus
              = link_to preview_backend_activity_path(activity), title: 'Lista uczestników' do
                i.btn.btn-warning
                  i.fa.fa-search
            td
              = activity.name
            td
              = empty_info(activity.description, "--BRAK OPISU--")
            td
              = show_status(activity.active)
            td
              = activity.day_of_week
            td
              = l(activity.start_on, format: :short)
            td
              = l(activity.end_on, format: :short)
            td
              = link_to pool_zone_backend_activities_path(zone: activity.pool_zone) do
                .btn.btn-warning
                  = activity.pool_zone
            td
              = link_to backend_person_path(activity.person) do
                = activity.person.full_name
            td
              = empty_info(activity.max_people, "--BRAK OGRANICZENIA--")

  = will_paginate @activities, renderer: BootstrapPagination::Rails

app/views/backend/activities/preview.html.slim
= render 'shared/back'
h5 Uczestnicy zajęcia grupowego
= info("Jesteś na stronie prezentującej uczestników zajęcia zapisanych \
        na najbliższe terminy.")

- unless @activities_people.blank?
  - @activities_people.each do |ap|
    .row
      .col-md-6
        ul.collection
          li.collection-item
            h5
              | Data:
              |  #{l(ap.date)}
    table.table.table-striped.table-bordered.table-list
      thead
        tr
          th
            | Nazwa
          th
            | Ilość uczestników
          th
            | Uczestnicy
      tbody
        tr
          td
            = @activity.name
          td
            = @activity.activities_people.where('date = ?', ap.date).count
            |  /
            = empty_info(@activity.max_people, "--BRAK OGRANICZENIA--")
          td
            - if @activity.activities_people.present?
              - @activity.activities_people.where('date = ?', ap.date).each_with_index do |a, i|
                = link_to backend_person_path(a.person.id) do
                  = a.person.full_name
                - if i < @activity.activities_people.where('date = ?', ap.date).size - 1
                  |,
- else
  .alert.alert-info
    | Brak uczestników

app/views/backend/activities/requests.html.slim
h5 Zajęcia czekające na zatwierdzenie
= info("Jesteś na stronie listy zajęć, które czekają na zatwierdzenie dołączenia \
        ich do aktywności odbywających się na terenie aquaparku.")
.col-md-6
  = render 'shared/a_searchbar'
table.table.table-striped.table-bordered.table-list.pretty.table-list-search
  thead
    tr
      - if current_receptionist || current_manager
        th
          em.fa.fa-cog
          |  Zarządzanie
      th
        = sortable "name", "Nazwa"
      th
        = sortable "description", "Opis"
      th
        = sortable "active", "Aktywne?"
      th
        = sortable "day_of_week", "Dzień tygodnia"
      th
        = sortable "start_on", "Godzina rozpoczęcia"
      th
        = sortable "end_on", "Godzina zakończenia"
      th
        = sortable "pool_zone", "Strefa basenu"
      th
        = sortable "people.first_name", "Trener"
      th
        = sortable "max_people", "Maksymalna ilość osób"
  tbody
    - @activity_requests.each do |activity|
      tr
        - if current_receptionist || current_manager
          td
            = link_to edit_backend_activity_path(activity), title: 'Edytuj' do
              i.btn.btn-default
                i.fa.fa-pencil
            = link_to activate_backend_activity_path(activity, active: true), title: 'Aktywuj', method: :post do
              i.btn.btn-success
                i.fa.fa-calendar-plus-o

        td
          = activity.name
        td
          = empty_info(activity.description, "--BRAK OPISU--")
        td
          = show_status(activity.active)
        td
          = activity.day_of_week
        td
          = l(activity.start_on, format: :short)
        td
          = l(activity.end_on, format: :short)
        td
          = link_to pool_zone_backend_activities_path(zone: activity.pool_zone) do
            .btn.btn-warning
              = activity.pool_zone
        td
          = link_to backend_person_path(activity.person) do
            = activity.person.full_name
        td
          = empty_info(activity.max_people, "--BRAK OGRANICZENIA--")

= will_paginate @activity_requests, renderer: BootstrapPagination::Rails

app/views/backend/activities/search.html.slim
= link_to backend_activities_path do
  .btn.btn-primary.waves-effect.waves-light
    i.fa.fa-chevron-left
    |  Wróć
h5 Rezultat wyszukiwania
= info("Jesteś na stronie prezentującej wyniki wyszukiwania dot. zajęć grupowych.")
.col-md-6
  = render 'shared/a_searchbar'
table.table.table-striped.table-bordered.table-list.pretty.table-list-search
  thead
    tr
      th
        em.fa.fa-cog
        |  Zarządzanie
      th
        | Nazwa
      th
        | Opis
      th
        | Aktywne?
      th
        | Dzień tygodnia
      th
        | Godzina rozpoczęcia
      th
        | Godzina zakończenia
      th
        | Strefa basenu
      th
        | Trener
      th
        | Maksymalna ilość osób
  tbody
    - unless @activities.blank?
      - @activities.each do |activity|
        tr
          td
            - if current_receptionist || current_manager
              = link_to edit_backend_activity_path(activity), title: 'Edytuj' do
                i.btn.btn-default
                  i.fa.fa-pencil
              = link_to backend_activity_path(activity), title: 'Usuń', method: :delete, data: {confirm: 'Jesteś pewny/a?'} do
                i.btn.btn-danger
                  i.fa.fa-trash
              - if activity.active
                - if current_receptionist || current_manager
                  = link_to deactivate_backend_activity_path(activity, active: false), title: 'Deaktywuj', method: :post do
                    i.btn.btn-danger
                      i.fa.fa-calendar-minus-o
              - unless activity.active
                = link_to activate_backend_activity_path(activity, active: true), title: 'Aktywuj', method: :post do
                  i.btn.btn-success
                    i.fa.fa-calendar-plus-o
            = link_to sign_up_backend_activity_path(activity), title: 'Dołącz' do
              i.btn.btn-success
                i.fa.fa-user-plus
            = link_to preview_backend_activity_path(activity), title: 'Lista uczestników' do
              i.btn.btn-warning
                i.fa.fa-search
          td
            = activity.name
          td
            = empty_info(activity.description, "--BRAK OPISU--")
          td
            = show_status(activity.active)
          td
            = activity.day_of_week
          td
            = l(activity.start_on, format: :short)
          td
            = l(activity.end_on, format: :short)
          td
            = link_to pool_zone_backend_activities_path(zone: activity.pool_zone) do
              .btn.btn-warning
                = activity.pool_zone
          td
            = link_to backend_person_path(activity.person) do
              = activity.person.full_name
          td
            = empty_info(activity.max_people, "--BRAK OGRANICZENIA--")
      = will_paginate @activities, renderer: BootstrapPagination::Rails
    - else
      tr
        td colspan='10'
          .text-center
            | Brak rezultatów.